### ISSUE TITLE
How do you connect your python script with this app?

### ISSUE THREAD

**Issue by 1001QAdotNET** [cmsirbu/tiny-flask#1]
For those of us who are not familiar with Flash....how to you get "arandoscript.py" to be called from the guy, and the results send back to the GUI ...where is the insertion point?

**Comment by cmsirbu** [comment]
Look at  https://github.com/cmsirbu/tiny-flask/blob/3936058d347fec3d8f7479d0f19498d4ff260ec7/tinyflask/views.py#L7-L9 - that function renders your index page (the "/" path). So to put it simply you could import your code and call it from the `index` function, then return its results as text... or use the template rendering engine if you want nicer looking html.

I suggest you read the quickstart and/or the Flask tutorial for more details: http://flask.pocoo.org/docs/1.0/
